version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server
    environment:
      SA_PASSWORD: "Senha@123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - db
    volumes:
      - ./db-init:/scripts
    entrypoint: >
      bash -c "
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S db -U sa -P 'Senha@123' -d GameCollection -i /scripts/insert_games_and_genres.sql
      "
    restart: "no"

  backend:
    build:
      context: ./backend/game_library_backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - ASPNETCORE_URLS=http://+:5102
      - ConnectionStrings__DefaultConnection=Server=db,1433;Database=GameCollection;User Id=sa;Password=Senha@123;TrustServerCertificate=True;    
    ports:
      - "5102:5102"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  sql-data:
